### ISSUE TITLE
Switch APRS SSID to new values

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-configs#1]
Please switch source and location SSIDs to those listed in the [OreSat APRS Header](https://docs.google.com/document/d/1gYe_WxVkGzgNJl752F_rJQmdJALE3-15hB1A2Xo8JYc/edit#heading=h.d08m74ici087) document.

**Comment by ryanpdx** [comment]
Done via 8aba733ed91ef8e50c2ed0714269f88ff4420238

**Comment by aSmig** [comment]
https://github.com/oresat/oresat-configs/blob/master/docs/beacon.rst SSID values appear to have fallen out of sync with this change.

Also, did C-Bit and reserved bits in the SSID byte get defined somewhere else? Since leftward bitshifting is mentioned, I assume Address Extension bits are handled elsewhere. If C-Bit and Reserved bits aren't defined elsewhere, then we should at least get those set for now with SSID 0x30 and 0x7B to land on 0x60 and 0xF7 after shifting and address termination.

Finally, since OreSat0 and OreSat0.5 will not have identical AX.25 headers, perhaps the shared static beacon.rst should call out those differences.

**Comment by ryanpdx** [comment]
I will move the `beacon.rst` page contents into the generate beacon pages, so it can correct values on a mission basis.

The `src_ssid` and `dest_ssid` fields are full octet, so it includes the C-Bit, reserve bits SSID bits, and the Address Extension bit before the bit shift.

For the mission differences would adding the default values  to `beacon.yaml` work? The defaults were in the `c3.yaml` config in the beacon record, but defaults can be read from the `beacon.yaml` just like the revision number.
```yaml
revision: 0
ax25:
  dest_callsign: SPACE
  dest_ssid: 0 # primary station
  src_callsign: KJ7SAT
  src_ssid: 11 # balloons, aircraft, spacecraft, etc
  control: 0x3 # ui-frame
  pid: 0xf0 # no L3 protocol
fields:
  # c3
  - [beacon, start_chars]
  - [satellite_id]`
 ...
```

All values are pre bit shift.
